server:
  context-path: /weixincp
  port: 8006

  logging:
  path: ../logs

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1/uaa/current
      id: ${spring.application.name:}
    client:
      clientId: server
      clientSecret: server
      accessTokenUri: http://127.0.0.1/uaa/oauth/token
      grant-type: client_credentials
      scope: server
spring:
  rabbitmq:
    host: 192.168.6.201
    port: 5672
    username: root
    password: root
  sleuth:
    sampler:
      percentage: 1
  datasource:
    url: jdbc:mysql://192.168.6.201:3306/zwwxcp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    db-name: zwwxcp
  redis:
    host: 127.0.0.1
    port: 6379
    database: 8
    timeout: 0
    pool:
      max-active: 100
      max-wait: 5
      max-idle: 50
      min-idle: 0
        
zw:
  swagger2:
    enable: true
    base-package: com.weiyan.zw
    title : Cola-Cloud
    description: Cola cloud Restful API docs
    termsOfServiceUrl : http://localhost:4000
    version: 1.0
    apiName: Authorization
    apiKeyName: Authorization

#mybatis配置
mybatis-plus:
  global-config:
    id-type: 1  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

management:
  security:
    enabled: false

eureka:
  instance:
    health-check-url-path: /health
    status-page-url-path: /info
    metadata-map:
      management.context-path: ${server.context-path:}